### ISSUE TITLE
Datelife not using all OToL trees

### ISSUE THREAD

**Issue by hdliv** [phylotastic/datelife#9]
there are some funny things going on.  I will comment later on what i see later

**Comment by bomeara** [comment]
It's later. :wink:

**Comment by hdliv** [comment]
haha.  So I went back and forth with Joseph, and we think it is involving this issue: OpenTreeOfLife/oti    find_trees failing #41  

what do you think?

**Comment by josephwb** [comment]
The original study indexer `oti` is apparently buggy, one instance of which is failing to find trees/studies that meet some criteria. No one seems to know how/why this fails, and no one is looking because a new indexer `otindex` has been in development for several months now. Once it is live this should no longer be an issue.

**Comment by josephwb** [comment]
This should probably be closed, as it is an OT issue rather than a datelife issue, but I'll leave it to @bomeara to do it in case he wants to leave this as a reminder that code may require updating to adapt to `otindex`. :blowfish:
